FROM nginx:1.22
WORKDIR /home/debian/BaseApp/frontend
COPY nginx.conf /home/debian/BaseApp/frontend/.
COPY index.html /home/debian/BaseApp/frontend/.
COPY style.css /home/debian/BaseApp/frontend/.
EXPOSE 80
